---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "hamhook.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
  {{- include "hamhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
