---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "hamhook.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
  {{- include "hamhook.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "hamhook.fullname" . }}.{{ .Release.Namespace }}.svc'
  issuerRef:
    name: '{{ include "hamhook.fullname" . }}'
  secretName: {{ include "hamhook.fullname" . }}-certificate