---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hamhook.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
  {{- include "hamhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hamhook
  template:
    metadata:
      labels:
        app: hamhook
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: hamhook
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 10 }}
          {{- end }}
          ports:
          - containerPort: 8443
          volumeMounts:
          - mountPath: /certs
            name: cert
            readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: {{ include "hamhook.fullname" . }}-certificate