---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hamhook.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
  {{- include "hamhook.labels" . | nindent 4 }}
spec:
  selector:
    app: hamhook
  ports:
    - port: 443
      targetPort: 8443